config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/pedidos', to: 'static_pages#pedidos'
  get  '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
  
   # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
     flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

def destroy
    log_out
    redirect_to root_url
end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def pedidos
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
before_action :correct_user,   only: [:edit, :update]
before_action :admin_user,     only: :destroy 


  def index
    @users=User.all
  end

  def show
  @user = User.find(params[:id])
  end

  def new
  @user = User.new
  end
  
  def create
    @user = User.new(user_params) #user params son solo los permitidos (ver más adelante)
    if @user.save
      log_in @user #una vez que salvaste te logguea!
      # Handle a successful save. y redirige al profile del usuario:
        flash[:success] = "Benviendo a a App de Capsulas de Empleados!"
        redirect_to @user
    else
      render 'new'
    end
  end

 def edit
    @user = User.find(params[:id])
 end

def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
end

def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
end

  private

    def user_params #Defino los permitodos a agregar:  habría que agregar el sitio de trabajo (btq/área de oficina)
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :area)
    end
       # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end  
    
     # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper


  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Capsulas Empleados"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
    # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
   
    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
   # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
    # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      <p>Realizado Por URIEL SENDYK - Nespresso Supply Chain</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Capsulas Empleados App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
         <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Mi Perfil <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Ver", current_user %></li>
              <li><%= link_to "Modificar", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        
        <li><%= link_to "Pedidos", pedidos_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
       <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<% provide(:title, "About") %>
  <h1> Contacto</h1>
  <p>Esta Web App fue creada por Uriel Sendyk (R)</p>
  <p>Contacto: <a href="mailto:uriel.sendyk@nespresso.com">Uriel Sendyk</a></p>
  
  <p>FORMULARIO DE CONTACTO</p>
<img src="" alt="">

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
  <h1>Bienvenido al sistema de Capsulas de Empleados</h1>
  <p>Ingrese</p>
<img src="" alt="">

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<div class="center jumbotron">
  <h1>Capsulas de Empleados </h1>

  <h2>
   Bienvenidos a la web de beneficio de capsulas de empleados de 
    <a href="https://www.nespresso.com.ar/">Nespresso</a>
  
  </h2>
  <%= link_to "Nuevo Usuario", signup_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Nuevo Pedido", "#", class: "btn btn-lg btn-primary" %>
  <%= link_to "Consultar / Modificar Pedido", "#", class: "btn btn-lg btn-primary" %>
</div>

<div class= logoness>
<%= link_to image_tag("nespresso logo.png", alt: "Nespresso"),
            'http://www.nespresso.com.ar/' %>
</div>

app/views/static_pages/pedidos.html.erb
<!DOCTYPE html>
<% provide(:title, "Pedidos") %>
  <h1>Ingrese su pedido de cápsulas</h1>
  <p></p>
<img src="" alt="">

app/views/users/edit.html.erb
<% provide(:title, "") %>
<h1>Modificar Datos</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Guardar", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
       <%= link_to user.name, user %> <br>|
       <%= link_to user.email, user %>
    
     <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
    
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Nuevo Usuario') %>
<h1>Creación de nuevo usuario</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear Nuevo Usuario", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>